config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix => 'my'

  namespace :admin do
    root to: 'admin/posts#index'
    resources :users
    resources :posts do
      resources :comments do
        member do
          put :publish
          put :unpublish
        end
      end
    end
  end

  root to: 'posts#index'

  resources :posts do
    resources :comments do
      member do
        put :publish
        put :unpublish
      end
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  #default_scope -> { where(published: true) }
  validates :body, presence: true, length: {minimum: 1, maximum: 400}

  def publish?
    self.published
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  before_action :find_comment, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  before_action :find_post
  before_action :authenticate_user!
  before_action :user_admin


  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if current_user.try(:admin?) || current_user.try(:mod?)
      @comment.published = true
    end
    if @comment.save
      redirect_to(admin_post_comments_path)
    else
      flash.now[:danger] = "error"
    end
  end

  def index
    @comments = Comment.where(post_id: @post.id).paginate(page: params[:page], per_page: 20)
  end

  def show
  end

  def new
    @comment = Comment.new
    authorize [:admin, @comment]
  end

  def destroy
    authorize [:admin, @comment]
    @comment.destroy
    redirect_back(fallback_location: root_path)
    flash[:success] = "deleted comment"
  end

  def edit
    authorize [:admin, @comment]
  end

  def update
    authorize [:admin, @comment]
    if @comment.update_attributes(comment_params)
      redirect_to @post
      flash[:success] = "Updated comment"
    else
      render 'edit'
    end
  end

  def publish
    authorize [:admin, @comment]
    @comment.published = true
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def unpublish
    authorize [:admin, @comment]
    @comment.published = false
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :id)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def user_admin
    redirect_to posts_path unless current_user.try(:admin?) || current_user.try(:mod?)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  before_action :find_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if current_user.try(:admin?) || current_user.try(:mod?)
      @comment.published = true
    end
    if @comment.save
      redirect_to @post
    else
      flash.now[:danger] = "error"
    end
  end

  def publish
    authorize @comment
    @comment.published = true
    @comment.save
    redirect_to @post
  end

  def unpublish
    authorize @comment
    @comment.published = false
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def edit
    authorize @comment
  end

  def update
    if @comment.update_attributes(comment_params)
      redirect_to @post
      flash[:success] = "Updated comment"
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_back(fallback_location: root_path)
    flash[:success] = "deleted comment"
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :id)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.erb
<h3>Post a comment</h3>

<%= form_for([ @post, @comment ], url: admin_post_comments_path(@post.id)) do |f| %>
  <p>
  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 2 %>
  </div>
  </p>
  <p>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </p>
  <br>
<% end %>

app/views/admin/comments/edit.html.erb
<div class="manage-header">
  <h3>
    Edit comment
    <small>
      <% if @comment.published %>
        <%= link_to 'unpublish', unpublish_admin_post_comment_path(params[:post_id], @comment.id), method: :put, data: {confirm: "Are you sure you want to unpublish this?"} %>
      <% else %>
        <%= link_to 'publish', publish_admin_post_comment_path(params[:post_id], @comment.id), method: :put, data: {confirm: "Are you sure you want to publish this?"} %>
      <% end %>
    </small>
  </h3>
</div>

<%= form_for(@comment, url: admin_post_comment_path(params[:post_id])) do |f| %>
  <p>
    <%= f.text_area :body, class: 'form-control', rows: 2  %>
  </p>
  <p>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </p>
  <br>
<% end %>

app/views/admin/comments/index.html.erb
<div class="manage-header">
  <h1>Manage Post Comments <%= content_tag(:small, link_to('new', new_admin_post_comment_path(params[:post_id]))) %></h1>
</div>

<table class="my-table">
  <tr>
    <th class="my-th">post_id</th>
    <th class="my-th">user</th>
    <th class="my-th">body</th>
    <th class="my-th">date</th>
    <th class="my-th">publish_comment</th>
    <th class="my-th">show_comment</th>
    <th class="my-th">edit_comment</th>
    <th class="my-th">delete_comment</th>
  </tr>
  <% @comments.each do |c| %>
    <tr>
      <td class="my-td"><%= link_to "#{c.post_id}", admin_post_path(params[:post_id]) %></td>
      <td class="my-td"><%= c.user.name %></td>
      <td class="my-td"><%= c.body %></td>
      <td class="my-td"><%= c.created_at %></td>
      <td class="my-td">
        <% if c.published %>
          <%= link_to 'unpublish', unpublish_admin_post_comment_path(params[:post_id], c.id), method: :put, data: {confirm: "Are you sure you want to unpublish this?"} %>
        <% else %>
          <%= link_to 'publish', publish_admin_post_comment_path(params[:post_id], c.id), method: :put, data: {confirm: "Are you sure you want to publish this?"} %>
        <% end %>
      </td>
      <td class="my-td"><%= link_to 'show', admin_post_comment_path(params[:post_id], c.id) %></td>
      <td class="my-td"><%= link_to 'edit', edit_admin_post_comment_path(params[:post_id], c.id) %></td>
      <td class="my-td"><%= link_to 'delete', admin_post_comment_path(params[:post_id], c.id), method: :delete, data: {confirm: "Are you sure you want to delete this permanently?"} %></td>
    </tr>
    <% end %>
</table>

<div class="my-pagination">
<%= will_paginate @comments %>
</div>

app/views/admin/comments/new.html.erb
<h3>Post a comment</h3>

<%= form_for(@comment, url: admin_post_comments_path(params[:post_id])) do |f| %>
  <p>
    <%= f.text_area :body, class: 'form-control', rows: 2 %>
  </p>
  <p>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </p>
  <br>
<% end %>

app/views/admin/comments/show.html.erb
<div class="comment-show">
  <p><small><strong>Added by: </strong><%= @comment.user.name %><strong>  at: </strong><%= @comment.created_at %></small></p>
  <p><%= @comment.body %></p>
</div>