config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix => 'my'

  namespace :admin do
    root to: 'admin/posts#index'
    resources :users
    resources :posts do
      resources :comments do
        member do
          put :publish
          put :unpublish
        end
      end
    end
  end

  root to: 'posts#index'

  resources :posts do
    resources :comments do
      member do
        put :publish
        put :unpublish
      end
    end
  end

end

app/views/layouts/_admin_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Nowik Blog", root_path, class: 'logo' %></li>
        <li><%= link_to "Admin Panel", admin_posts_path, class: 'logo' %></li>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Manage Posts', admin_posts_path %></li>
        <li><%= link_to 'Manage Users', admin_users_path %></li>
        <% if current_user %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

          <% if current_user.avatar.attached? %>
            <li class="round-image-50"><%= image_tag(current_user.avatar) %></li>
          <% else %>
            <li class="round-image-50"><%= image_tag gravatar_image_url(current_user.email) %></li>
          <% end %>

        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_flash_messages.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"/>

<% flash.each do |message_type, message| %>
  <div class="<%= "alert alert-#{message_type}" %>">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">

  <div class="footer-copyright text-center ">
    Paweł Nowik &copy; 2019 Wszelkie prawa zastrzeżone.
  </div>

</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Nowik Blog", root_path, class: 'logo' %></li>
        <% if current_user.try(:admin?) || current_user.try(:mod?) %>
          <li><%= link_to "Admin Panel", admin_posts_path, class: 'logo' %></li>
        <% end %>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Posts', posts_path %></li>
        <% if current_user %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

          <% if current_user.avatar.attached? %>
            <li class="round-image-50"><%= image_tag(current_user.avatar) %></li>
          <% else %>
            <li class="round-image-50"><%= image_tag gravatar_image_url(current_user.email) %></li>
          <% end %>

        <% else %>
          <li><%= link_to 'Register', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Interface</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin/users/show'%>
    <%= javascript_pack_tag 'admin/users/edit'%>
    <%= javascript_pack_tag 'admin/users/index'%>
  </head>


  <body>

    <%= render 'layouts/flash_messages' %>
    <%= render 'layouts/admin_menu' %>


    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NowikBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_messages' %>
    <%= render 'layouts/menu' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>